# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
api_key: admin
galaxy_instance: http://localhost:8080
install_repository_dependencies: True
install_resolver_dependencies: True
install_tool_dependencies: False
tools:

########### QC
- name: fastqc
  owner: devteam
  tool_panel_section_id: 'qc'

- name: multiqc
  owner: iuc
  tool_panel_section_id: 'qc'
  
- name: trimmomatic
  owner: pjbriggs
  tool_panel_section_id: 'qc'

#####################
#####################
#####################
